---
k3s_version: v1.24.3+k3s1
ansible_user: sean
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: " --disable traefik --disable servicelb server"
extra_agent_args: ""
