---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.visonneau.fr
      chart: tailscale-relay
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: mvisonneau
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicas: 1
    annotations:
      secret.reloader.stakater.com/reload: tailscale-relay-secret
    image:
      repository: docker.io/mvisonneau/tailscale
      pullPolicy: IfNotPresent
      tag: 'v1.36.1'
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
    config:
      variables:
        TAILSCALE_ADVERTISE_EXIT_NODE: "true"
        TAILSCALE_ADVERTISE_ROUTES: "${NETWORK_K8S_POD_CIDR},${NETWORK_BGP_SVC_CIDR},10.0.16.0/24"
        TAILSCALE_HOST_ROUTES: "true"
  valuesFrom:
    - kind: Secret
      name: tailscale-relay-secret
      valuesKey: tailscale-token
      targetPath: config.authKey