---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8sinterpreter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: k8sinterpreter-secret
    template:
      data:
        MINIO_ACCESS_KEY: "{{ .MINIO_ROOT_USER }}"
        MINIO_SECRET_KEY: "{{ .MINIO_ROOT_PASSWORD }}"
        API_KEY: "{{ .K8SINTERPRETER_API_KEY }}"
        MASTER_API_KEY: "{{ .K8SINTERPRETER_MASTER_API_KEY }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: k8sinterpreter
