---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8sinterpreter
spec:
  interval: 30m
  url: https://github.com/wipash/K8sInterpreter
  ref:
    branch: main
    # or use a tag: tag: v1.1.1
  ignore: |
    # exclude all
    /*
    # include helm chart directory
    !/helm-deployments/librecodeinterpreter
