---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app e1000e-fix
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/networking/e1000e-fix/app
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  wait: false
  interval: 10m
