---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./authelia/ks.yaml
  #- ./bazarr/ks.yaml
  - ./cloudnative-pg/ks.yaml
  - ./cyberchef/ks.yaml
  - ./frigate/ks.yaml
  - ./ghcr-imagepullsecret/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homebox/ks.yaml
  - ./homepage/ks.yaml
  - ./immich/ks.yaml
  - ./lldap/ks.yaml
  - ./mealie/ks.yaml
  - ./miniflux/ks.yaml
  - ./mosquitto/ks.yaml
  - ./node-red/ks.yaml
  - ./overseerr/ks.yaml
  - ./paperless/ks.yaml
  - ./plex/ks.yaml
  - ./postgres-backup/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./shlink/ks.yaml
  - ./smokeping/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./sonarr/ks.yaml
  #- ./sparkleandspin/ks.yaml
  - ./tautulli/ks.yaml
  - ./unifi/ks.yaml
  - ./wordpress/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  #- ./openwebui/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./readarr/ks.yaml
  - ./plandex/ks.yaml
  - ./excalidraw/ks.yaml
  - ./openproject/ks.yaml
