---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plandex
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: plandex-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: |-
          postgres://{{ .PLANDEX_POSTGRES_USER }}:{{ .PLANDEX_POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local/plandex
        SMTP_USER: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        INIT_POSTGRES_DBNAME: plandex
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .PLANDEX_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .PLANDEX_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: plandex
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp-relay
