---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./emberstack.yaml
  - ./groundhog2k.yaml
  - ./jetstack.yaml
  - ./k8sathome.yaml
  - ./nfs-subdir-external-provisioner.yaml
  - ./runix.yaml
  - ./ingress-nginx.yaml
  - ./kubito.yaml
  - ./stakater-charts.yaml
  - ./node-feature-discovery.yaml
  - ./kubernetes-sigs-descheduler-charts.yaml
  - ./prometheus-community-charts.yaml
  - ./metricsserver.yaml
  - ./hajimari.yaml
  - ./cetic.yaml
  - ./cilium.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./bjw-s.yaml
  - ./mvisonneau.yaml
  - ./weave-gitops.yaml
  - ./piraeus.yaml
  - ./external-secrets.yaml
  - ./rook-ceph.yaml
  - ./intel.yaml
  - ./vector.yaml
  - ./kyverno.yaml
  - ./descheduler.yaml
  - ./actions-runner-controller.yaml
  - ./democratic-csi.yaml
  - ./cloudnative-pg.yaml
  - ./openebs.yaml
  - ./spegel.yaml
  - ./coredns.yaml
  - ./postfinance.yaml
  - ./tailscale.yaml
  - ./external-dns.yaml
