---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookstack
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bookstack-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # bookstack
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        #OIDC_CLIENT_SECRET: "{{ .BOOKSTACK_OAUTH_CLIENT_SECRET }}" # from authelia
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_ISSUER: "{{ .OIDC_ISSUER }}"
  dataFrom:
    - extract:
        key: bookstack
    # - extract:
    #     key: authelia
