# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.3.3

# Cache settings: Set to true to enable caching
cache: true

# Custom interface configuration
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: false
  bookmarks: true
  multiConvo: true
  runCode: true
  webSearch: true
  peoplePicker:
    users: true
    groups: true
    roles: true
  marketplace:
    use: true
  fileCitations: true
  prompts:
    use: true
    share: true
    public: true
  agents:
    use: true
    share: true
    public: true
  mcpServers:
    use: true
    create: true
    share: true
    public: true
    trustCheckbox:
      label: I understand and I want to continue
      subLabel: Malicious MCP servers may attempt to steal your data or trick the model into taking unintended actions, including destroying data.


speech:
  speechTab:
    conversationMode: false
    advancedMode: false
    speechToText:
      engineSTT: "external"
      languageSTT: "English (New Zealand)"
      autoTranscribeAudio: true
      decibelValue: -45
      autoSendText: 0
    textToSpeech:
      engineTTS: "external"
      voice: "alloy"
      languageTTS: "en"
      automaticPlayback: false
      playbackRate: 1.0
      cacheTTS: true
  tts:
    openai:
      apiKey: "$${SPEECH_API_KEY}"
      model: "gpt-4o-mini-tts"
      voices: ["alloy", "echo", "fable", "onyx", "nova", "shimmer"]
  stt:
    openai:
      apiKey: "$${SPEECH_API_KEY}"
      model: "gpt-4o-transcribe"

ocr:
  mistralModel: mistral-ocr-latest
  apiKey: "$${MISTRAL_API_KEY}"
  strategy: mistral_ocr

webSearch:
  serperApiKey: "$${SERPER_API_KEY}"
  searchProvider: "serper"

  firecrawlApiKey: "$${FIRECRAWL_API_KEY}"
  scraperType: "firecrawl"

  cohereApiKey: "$${COHERE_API_KEY}"
  rerankerType: "cohere"

  scraperTimeout: 7500
  safeSearch: 1

rateLimits:
  fileUploads:
    userMax: 50
    userWindowInMinutes: 60 # Rate limit window for file uploads per user
  conversationsImport:
    ipMax: 100
    ipWindowInMinutes: 60 # Rate limit window for conversation imports per IP
    userMax: 50
    userWindowInMinutes: 60 # Rate limit window for conversation imports per user

fileConfig:
  endpoints:
    agents:
      supportedMimeTypes:
        - "^application/pdf$"
        - "^application/vnd\\.openxmlformats-officedocument\\.(wordprocessingml\\.document|presentationml\\.presentation|spreadsheetml\\.sheet)$"
        - "^application/vnd\\.ms-(word|powerpoint|excel)$"
        - "^application/vnd\\.ms-(excel|powerpoint|word)\\..+\\.macro[eE]nabled\\.12$"
        - "^application/epub\\+zip$"
        - "text/.*"
        - "image/.*"
  serverFileSizeLimit: 200
  avatarSizeLimit: 2
  imageGeneration:
    percentage: 100
    px: 1024
  clientImageResize:
    enabled: true
    maxWidth: 1900
    maxHeight: 1900
    quality: 0.92

endpoints:
  custom:
    - name: LiteLLM
      apiKey: "$${LITELLM_API_KEY}"
      baseURL: "https://litellm2.hlms.cloud"
      models:
        default: ["azure/gpt-5"]
        fetch: true
      titleConvo: true
      titleModel: "azure/gpt-5-nano"
      modelDisplayLabel: "LiteLLM"

  assistants:
    disableBuilder: true

  agents:
    disableBuilder: false
    capabilities:
      - "execute_code"  # This requires an API key
      - "file_search"
      - "actions"
      - "tools"
      - "artifacts"
      - "ocr"
      - "chain"
      - "web_search"
      - "context"


  all:
    streamRate: 10 # Higher number 'buffers' incoming chunks to make the output smoother

modelSpecs:
  enforce: false
  prioritize: false
  addedEndpoints: ["openAI", "google", "anthropic", "LiteLLM", "agents"]
  list:
    - name: claude
      label: Claude
      description: Claude
      iconURL: https://holmesazaepubshare.blob.core.windows.net/logosandicons/sherlock/claude.png
      showIconInMenu: true
      showIconInHeader: true
      default: false
      preset:
        endpoint: agents
        agent_id: agent_6SgjYIhwhpWodbr3XeYGn

    - name: gpt
      label: GPT-5.2
      description: GPT-5.2
      iconURL: https://holmesazaepubshare.blob.core.windows.net/logosandicons/sherlock/chatgpt-blue.png
      showIconInMenu: true
      showIconInHeader: true
      default: false
      preset:
        endpoint: agents
        agent_id: agent_K7CjEugZnIVs-9Kxycxpn

    - name: gemini
      label: Gemini
      description: Google Gemini 3 Flash
      iconURL: "https://holmesazaepubshare.blob.core.windows.net/pub/gemini.png"
      showIconInMenu: true
      showIconInHeader: true
      default: false
      preset:
        endpoint: agents
        agent_id: agent_-AFN7SdqfbUc-aoC8Yix4
