---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: umami-secret
    template:
      data:
        DATABASE_URL: "postgresql://umami:{{ .POSTGRES_PASSWORD }}@postgres17-rw.database.svc.cluster.local:5432/umami"
        APP_SECRET: "{{ .APP_SECRET }}"
        IGNORE_IP: "{{ .IGNORE_IP_LIST }}"
        INIT_POSTGRES_DBNAME: umami
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: umami
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: umami
