---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librechat
spec:
  chartRef:
    kind: OCIRepository
    name: librechat
  interval: 1h
  values:
    controllers:
      librechat:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom: &envFrom
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
              - configMapRef:
                  name: "{{ .Release.Name }}-configmap"
        containers:
          app:
            image:
              repository: ghcr.io/danny-avila/librechat-dev
              tag: latest@sha256:3ea20d48a6d52ad54cb012661722c87e9a91653ff4339f1a71f6b96db0aa9836
            env:
              TZ: Pacific/Auckland
              PORT: "3080"
              NODE_ENV: "development"
              MONGO_URI: &mongo "mongodb://localhost:27017/LibreChat"

              # Disable these to just use LiteLLM
              # OPENAI_API_KEY: ""
              # ANTHROPIC_API_KEY: ""

            dependsOn:
              - mongodb
              - meilisearch
              - ragapi

            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1000Mi
            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: false

          exporter:
            dependsOn: app
            image:
              repository: ghcr.io/wipash/librechatmetrics
              tag: latest
            env:
              TZ: Pacific/Auckland
              MONGODB_URI: *mongo
              PROMETHEUS_PORT: &exporterport "9123"

          ragapi:
            image:
              repository: ghcr.io/danny-avila/librechat-rag-api-dev-lite
              tag: latest@sha256:293ebcfdc7118a8e7b67e569ccc278bd07e999e9718ce3c8bfa5bdbcafa40e88
            env:
              TZ: Pacific/Auckland
            envFrom: *envFrom
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes: *probes

          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.34.2
            args:
              - /bin/meilisearch
              - --experimental-dumpless-upgrade
            env:
              TZ: Pacific/Auckland
              MEILI_DB_PATH: "/meili_data"
            envFrom: *envFrom
            securityContext: *securityContext
            probes: *probes

          # litellm:
          #   image:
          #     repository: ghcr.io/berriai/litellm
          #     tag: main-v1.44.28
          #   command:
          #     ["litellm", "--config", "/app/litellm.yaml", "--port", "4000"]
          #   envFrom: *envFrom
          #   securityContext: *securityContext
          #   probes: *probes

          mongodb:
            image:
              repository: mongo
              tag: 8.2.4
            command: ["mongod", "--noauth"]
            env:
              TZ: Pacific/Auckland
            securityContext: *securityContext
            probes: *probes

          mongo-express:
            image:
              repository: mongo-express
              tag: 1.0.2@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64
            env:
              TZ: Pacific/Auckland
              ME_CONFIG_MONGODB_SERVER: 127.0.0.1
              ME_CONFIG_BASICAUTH_USERNAME: admin
              ME_CONFIG_BASICAUTH_PASSWORD: password
              PORT: 8081
            securityContext: *securityContext
            probes: *probes

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        ports:
          http:
            port: 3080
          mongo-express:
            port: 8081
          # litellm:
          #   port: 4000
          metrics:
            port: *exporterport

    ingress:
      app:
        className: external
        hosts:
          - host: &host chat.mcgrath.nz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

      mongo-express:
        className: internal
        hosts:
          - host: mongolibre.mcgrath.nz
            paths:
              - path: /
                service:
                  identifier: app
                  port: mongo-express
        tls:
          - hosts:
              - *host

    persistence:
      config:
        type: configMap
        name: librechat-config
        advancedMounts:
          librechat:
            app:
              - subPath: librechat.yaml
                path: /app/librechat.yaml

      app-data:
        type: emptyDir
        advancedMounts:
          librechat:
            app:
              - path: /app/data
              - path: /app/api/data
              - path: /app/logs

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          librechat:
            app:
              - subPath: logs
                path: /app/api/logs
              - subPath: images
                path: /app/client/public/images
              - subPath: uploads
                path: /app/uploads
            mongodb:
              - subPath: mongodb
                path: /data/db
            ragapi:
              - subPath: ragapi
                path: /app/uploads

      meilisearch:
        type: emptyDir
        # storageClass: ceph-block
        # accessMode: ReadWriteOnce
        # size: 1Gi
        advancedMounts:
          librechat:
            meilisearch:
              - path: /meili_data

    serviceMonitor:
      app:
        endpoints:
          - port: metrics
            scheme: http
            path: /
            interval: 1m
            scrapeTimeout: 30s
