---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: timelapse-processor
spec:
  chartRef:
    kind: OCIRepository
    name: timelapse-processor
  interval: 1h
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      timelapse-processor:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "0 7-19 * * *"  # At minute 0 past every hour from 07:00 through 19:00
          timeZone: &timeZone Pacific/Auckland
          successfulJobsHistory: 1
          failedJobsHistory: 1
        pod:
          restartPolicy: Never
        containers:
          app:
            image:
              repository: ghcr.io/wipash/northgrove-timelapse
              tag: main@sha256:e2eb1445dca7b47b5c056fda7acac25ef0667d1f20fb2884617477998a2390d3
            env:
              TZ: *timeZone
            envFrom:
              - secretRef:
                  name: timelapse-processor-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
      timelapse-full:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "0 2 * * 1"  # At 02:00 on Monday
          timeZone: *timeZone
          successfulJobsHistory: 1
          failedJobsHistory: 1
        pod:
          restartPolicy: Never
        containers:
          app:
            image:
              repository: ghcr.io/wipash/northgrove-timelapse
              tag: main@sha256:e2eb1445dca7b47b5c056fda7acac25ef0667d1f20fb2884617477998a2390d3
            args:
              - full
            env:
              TZ: *timeZone
            envFrom:
              - secretRef:
                  name: timelapse-processor-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 2000m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    persistence:
      cache:
        existingClaim: timelapse-processor-cache
        globalMounts:
          - path: /app/videos
      tmp:
        type: emptyDir
      uv-cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
