---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Infrastructure
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .unifi_user }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .unifi_pass }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .hass_token }}"
        ## Downloads
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .prowlarr_token }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .radarr_token }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .readarr_token }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .sonarr_token }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .lidarr_token }}"
        ## Selfhosted
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .paperless_token }}"
        HOMEPAGE_VAR_PIHOLE_TOKEN: "{{ .pihole_token }}"

        HOMEPAGE_VAR_HOME_LATITUDE: "{{ .home_latitude }}"
        HOMEPAGE_VAR_HOME_LONGITUDE: "{{ .home_longitude }}"
  data:
    ## Non Cluster
    - secretKey: unifi_user
      remoteRef:
        key: unifi
        property: username
    - secretKey: unifi_pass
      remoteRef:
        key: unifi
        property: password
    - secretKey: hass_token
      remoteRef:
        key: home-assistant
        property: CODE_ACCESS_TOKEN
    ## Downloads
    - secretKey: prowlarr_token
      remoteRef:
        key: prowlarr
        property: PROWLARR__API_KEY
    - secretKey: radarr_token
      remoteRef:
        key: radarr
        property: RADARR__API_KEY
    - secretKey: readarr_token
      remoteRef:
        key: readarr
        property: READARR__API_KEY
    - secretKey: sonarr_token
      remoteRef:
        key: sonarr
        property: SONARR__API_KEY
    - secretKey: lidarr_token
      remoteRef:
        key: lidarr
        property: LIDARR__API_KEY
    - secretKey: paperless_token
      remoteRef:
        key: paperless
        property: PAPERLESS_API_TOKEN
    - secretKey: pihole_token
      remoteRef:
        key: homepage
        property: PIHOLE_TOKEN
    - secretKey: home_latitude
      remoteRef:
        key: homepage
        property: HOME_LATITUDE
    - secretKey: home_longitude
      remoteRef:
        key: homepage
        property: HOME_LONGITUDE
